[tools]

colima = "latest"
lima = "latest"
docker-cli = "latest"
docker-compose = { version = "latest", postinstall = "rm ~/.docker/cli-plugins/docker-compose && ln -s $(mise which docker-cli-plugin-docker-compose) ~/.docker/cli-plugins/docker-compose" }
"aqua:docker/buildx" = { version = "latest", postinstall = "rm ~/.docker/cli-plugins/docker-buildx && ln -s $(mise which docker-cli-plugin-docker-buildx) ~/.docker/cli-plugins/docker-buildx" }
lazydocker = "latest"
hadolint = "latest"
"npm:@microsoft/compose-language-service" = "latest"