#!/bin/sh

# プッシュ先のリモート情報を取得
remote_name="$1"

# 現在のブランチ名を取得
current_branch=$(git rev-parse --abbrev-ref HEAD)

# ユーザーに確認を求める
echo >&2 "木村拓哉「ちょ待てよ。"${remote_name} : ${current_branch}" をプッシュするよ？」 ( y / n )"

# ユーザーからの入力を受け付ける
read -r answer </dev/tty

if [ "$answer" != "y" ]; then
	echo >&2 "プッシュを中止しました。"
	exit 1
fi

# 入力が "y" の場合はプッシュを継続（スクリプトを終了コード0で終了）
exit 0
