[settings]
minimum_release_age = "1h"

[env]

EDITOR = "nvim"
GIT_EDITOR = "nvim -u ~/.config/nvim/minimal.lua"
AWS_PROFILE = "floci"

[shell_alias]
dc = "docker compose"
dps = 'docker ps --format "table {{ "{{" }}.Names{{ "}}" }}\t{{ "{{" }}.Status{{ "}}" }}\t{{ "{{" }}.Ports{{ "}}" }}"'
dpsa = "docker ps -a"
dst = "docker stats"
dil = "docker images"
dclog = "docker compose logs -f --no-log-prefix"
dcex = "docker compose exec -it"
drm = "docker rm"
dri = "docker rmi"
dcl = '''docker system df && docker volume ls -qf dangling=true | xargs -r docker volume rm && docker images -f 'dangling=true' -q | xargs -r docker rmi && docker container prune --force --filter 'until=168h' && docker ps --filter 'status=exited' | grep 'weeks ago' | awk '{print $1}' | xargs -r docker rm && docker builder prune && docker system df'''
pn = "pnpm"